# These are the valid shapes that may be specified for an object.
string CIRCLE=circle
string SEMICIRCLE=semicircle
string QUARTER_CIRCLE=quarter_circle
string TRIANGLE=triangle
string SQUARE=square
string RECTANGLE=rectangle
string TRAPEZOID=trapezoid
string PENTAGON=pentagon
string HEXAGON=hexagon
string HEPTAGON=heptagon
string OCTAGON=octagon
string STAR=star
string CROSS=cross

# Object shape.
# Must be one of the constants defined above.
string data
