// Generated by gencpp from file storm32_gimbal/GimbalOrientation.msg
// DO NOT EDIT!


#ifndef STORM32_GIMBAL_MESSAGE_GIMBALORIENTATION_H
#define STORM32_GIMBAL_MESSAGE_GIMBALORIENTATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Quaternion.h>

namespace storm32_gimbal
{
template <class ContainerAllocator>
struct GimbalOrientation_
{
  typedef GimbalOrientation_<ContainerAllocator> Type;

  GimbalOrientation_()
    : orientation()
    , unlimited(false)  {
    }
  GimbalOrientation_(const ContainerAllocator& _alloc)
    : orientation(_alloc)
    , unlimited(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef uint8_t _unlimited_type;
  _unlimited_type unlimited;





  typedef boost::shared_ptr< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalOrientation_

typedef ::storm32_gimbal::GimbalOrientation_<std::allocator<void> > GimbalOrientation;

typedef boost::shared_ptr< ::storm32_gimbal::GimbalOrientation > GimbalOrientationPtr;
typedef boost::shared_ptr< ::storm32_gimbal::GimbalOrientation const> GimbalOrientationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::storm32_gimbal::GimbalOrientation_<ContainerAllocator1> & lhs, const ::storm32_gimbal::GimbalOrientation_<ContainerAllocator2> & rhs)
{
  return lhs.orientation == rhs.orientation &&
    lhs.unlimited == rhs.unlimited;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::storm32_gimbal::GimbalOrientation_<ContainerAllocator1> & lhs, const ::storm32_gimbal::GimbalOrientation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace storm32_gimbal

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "429b834c7e4456a2d8d33b9a6ac43342";
  }

  static const char* value(const ::storm32_gimbal::GimbalOrientation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x429b834c7e4456a2ULL;
  static const uint64_t static_value2 = 0xd8d33b9a6ac43342ULL;
};

template<class ContainerAllocator>
struct DataType< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "storm32_gimbal/GimbalOrientation";
  }

  static const char* value(const ::storm32_gimbal::GimbalOrientation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Quaternion orientation\n"
"bool unlimited\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::storm32_gimbal::GimbalOrientation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orientation);
      stream.next(m.unlimited);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalOrientation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::storm32_gimbal::GimbalOrientation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::storm32_gimbal::GimbalOrientation_<ContainerAllocator>& v)
  {
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "unlimited: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.unlimited);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STORM32_GIMBAL_MESSAGE_GIMBALORIENTATION_H
